### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [sarahleavitt/nbTransmission#1]
Thanks for updating nbTransmission earlier. We're still seeing problems related to https://github.com/igraph/rigraph/pull/1072#issuecomment-1879565501 from the vignette, see https://github.com/igraph/rigraph/blob/main/revdep/problems.md#nbtransmission for details.

We're planning to send igraph to CRAN on January 23. Apologies for the short notice.

Tracker issue: https://github.com/igraph/rigraph/issues/989.

**Comment by sarahleavitt** [comment]
Thank you! I didn't see this until getting a notification from CRAN. The issue was that I had a numeric variable stored as a factor (for other uses) and that was changed to character in the network. That is why I initially missed it. I fixed this issue in the next release.
